[package]
name = "kasaki-discord-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.10.9", features =  ["cache", "framework", "standard_framework", "rustls_backend"] }
tokio = { version = "1.0", features = ["macros", "signal", "rt-multi-thread"] }
dotenv = "0.15.0"
chrono = "0.4.19"
